name: Build test
on:
  push:
    branches:
      - test1
jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: bash ci.sh deps
    - name: Build LLVM
      run: bash build-toolchain.sh
    - name: GitHub release
      run: bash ci.sh release
